### ISSUE TITLE
Only Vault is Displayed In Browser ( Missing Characters ) 

### ISSUE THREAD

**Issue by N8torius** [kyleshay/DIM#184]
This bug happened over night...

I made no change in settings with my computer.
'Clicked the item manager icon and i got this. 

Please help.

![untitled](https://cloud.githubusercontent.com/assets/13459195/8839865/4f174d70-3097-11e5-8cf2-30d36a297667.png)

**Comment by N8torius** [comment]
@kyleshay

**Comment by nchase** [comment]
@N8torius: is this still happening for you? mine is fine.

**Comment by SunburnedGoose** [comment]
I'm working with someone on this. I'll update with results later.

**Comment by N8torius** [comment]
Yes still previews vault only i have restarted my computer.. turned off firewall... also re-downloaded the application.. this is an obvious Bug

**Comment by SunburnedGoose** [comment]
It's a bug with Bungie.net's JSON Response.  They are sending out of spec data.  I'll correct for it and send a update in a few.  

The issue is when you have a character with light level 20, the JSON data for your character sends a NaN for your progressToNextLevel attribute.  NaN is not a valid JSON attribute and so the error occurs.  I'll be replacing NaN with a 0 for now.

**Comment by N8torius** [comment]
LOL I had my old gear on while playing elimination on my warlock and didn't take it off. had no idea this would happen took off the gear and it works now haha THANKYOU
