### ISSUE TITLE
Stats added to items twice

### ISSUE THREAD

**Issue by SunburnedGoose** [kyleshay/DIM#39]
Which should be used?

https://github.com/kyleshay/DIM/blob/master/scripts/main.js#L663
https://github.com/kyleshay/DIM/blob/master/scripts/main.js#L673

**Comment by kyleshay** [comment]
oof. didn't notice that. 

[partial speculation] so, the _itemDefs.stats give the base stats. The item.stats give the current stats of the item (based on perks selected)

let's go with item.stats: https://github.com/kyleshay/DIM/blob/master/scripts/main.js#L673

1. provides actual stats based on selections made by user
2. _itemDefs[] file won't need to store item stats since we're getting that information anyway from the bungie request.
